FROM docker.io/owncloud/ubuntu:20.04@sha256:9cdc86249b1667ecec25b6f6db6a3d8e82a1ec7c7d09ca9916f3a3073ceefb83

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud CI PHP" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloudci/php" \
  org.opencontainers.image.source="https://github.com/owncloud-ci/php" \
  org.opencontainers.image.documentation="https://github.com/owncloud-ci/php"

VOLUME ["/var/www/owncloud"]

ENV ORACLE_HOME=/usr/lib/oracle/12.2/client64
ENV LD_LIBRARY_PATH=/usr/lib/oracle/12.2/client64/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
ENV APACHE_LOGGING_PATH=/dev/stdout

ARG RETRY_VERSION
ARG TARGETPLATFORM

# renovate: datasource=github-releases depName=owncloud-ci/retry
ENV RETRY_VERSION="${RETRY_VERSION:-v2.0.0}"

RUN curl -SsfL -o /usr/local/bin/retry "https://github.com/owncloud-ci/retry/releases/download/v${RETRY_VERSION##v}/retry" && \
  chmod 755 /usr/local/bin/retry

RUN apt-get update -y && \
  apt-get install -y software-properties-common language-pack-en-base && \
  LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php && \
  LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/apache2

RUN apt-get update -y && \
  apt-get upgrade -y && \
  apt-get install -y apache2 libapache2-mod-php7.4 libkrb5-dev libxml2-utils git-core unzip wget fontconfig libaio1 python2 php7.4 php7.4-dev php7.4-xml php7.4-mbstring php7.4-curl php7.4-gd php7.4-zip php7.4-intl php7.4-sqlite3 php7.4-mysql php7.4-pgsql php7.4-soap php7.4-phpdbg php7.4-ldap php7.4-gmp php7.4-imap php7.4-redis php7.4-memcached php7.4-imagick php7.4-smbclient php7.4-apcu php7.4-apcu-bc php7.4-ast rsync && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /etc/apache2/sites-available/default-ssl.conf && \
  a2enmod rewrite headers env dir mime ssl expires dav dav_fs

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
  curl -sSo oracle-instantclient12.2-basic_12.2.0.1.0-2_amd64.deb https://minio.owncloud.com/packages/oracle/oracle-instantclient12.2-basic_12.2.0.1.0-2_amd64.deb && \
  dpkg -i oracle-instantclient12.2-basic_12.2.0.1.0-2_amd64.deb && \
  rm oracle-instantclient12.2-basic_12.2.0.1.0-2_amd64.deb; \
  fi

RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
  curl -sSo oracle-instantclient12.2-sqlplus_12.2.0.1.0-2_amd64.deb https://minio.owncloud.com/packages/oracle/oracle-instantclient12.2-sqlplus_12.2.0.1.0-2_amd64.deb && \
  dpkg -i oracle-instantclient12.2-sqlplus_12.2.0.1.0-2_amd64.deb && \
  rm oracle-instantclient12.2-sqlplus_12.2.0.1.0-2_amd64.deb; \
  fi

RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
  curl -sSo oracle-instantclient12.2-devel_12.2.0.1.0-2_amd64.deb https://minio.owncloud.com/packages/oracle/oracle-instantclient12.2-devel_12.2.0.1.0-2_amd64.deb && \
  dpkg -i oracle-instantclient12.2-devel_12.2.0.1.0-2_amd64.deb && \
  rm oracle-instantclient12.2-devel_12.2.0.1.0-2_amd64.deb; \
  fi

RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
  ln -s /usr/include/oracle/12.2/client64 /usr/lib/oracle/12.2/client64/include && \
  echo "instantclient,/usr/lib/oracle/12.2/client64/lib" | pecl install oci8-2.2.0; \
  fi

RUN pecl -d php_suffix=7.4 install krb5

COPY overlay /
WORKDIR /var/www/owncloud
