workspace:
  base: /drone
  path: src

pipeline:
  dryrun:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: owncloudci/php
    label_schema:
      - name=PHP
      - version=${DRONE_BRANCH}
    dry_run: true
    tags: [ '7.0' ]
    when:
      event: [ pull_request ]

  docker:
    image: plugins/docker:17.05
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: owncloudci/php
    label_schema:
      - name=PHP
      - version=${DRONE_BRANCH}
    tags: [ '7.0' ]
    when:
      event: [ push ]
      branch: [ '7.0' ]

  microbadger:
    image: plugins/webhook:1
    pull: true
    secrets:
      - source: microbadger_token
        target: plugin_webhook
    when:
      event: [ push ]
      branch: [ '7.0' ]

  slack:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: drone
    when:
      status: [ success, failure ]
